### ISSUE TITLE
How can I test UnityCachePlusPlus?

### ISSUE THREAD

**Issue by jordiboni** [gabosgab/UnityCachePlusPlus#1]
Running the exe file, Unity don't connect using the preferences panel. Shall I change the port?

**Comment by jordiboni** [comment]
Ok, I was using Unity 5.3.4p6 and in this version, the port is 8126 and the version 254

**Comment by gabosgab** [comment]
Hi Jordi, Unity 5 is not yet supported.  I'll put it in the readme.

**Comment by jordiboni** [comment]
Ok, I'm trying to have a CacheServer and a LegacyCacheServer as the
official has.

I'll commit my changes if it works ;)
